# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a8d8dc406431aedfd5e971136450d18d3dec63e2dec2088ee3278c178f1e2cfaec58c225fbffb44ea51de83528c96309fe2cc07abc69762e29421436e09d39c

test:
  secret_key_base: 8681e34d5d80e617c73decdd49497b75ae62fe108bbfa07a2ee4d67ffed00a8565f1febe9682b4bba81484dc0e5bfa36f388b2cdbe0765c77b46b34e3c4fcc23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
